global:
  dnsZone: example.shop
  storeFrontUrl: https://www.example.shop
  stripeKey: YOUR_PRIVATE_STRIPE_API_KEY
admin:
  internalAlias: admin
  replicaCount: 2
  image:
    repository: reactioncommerce/admin
    tag: 3.0.0-beta.6
    pullPolicy: IfNotPresent
    # imagePullSecret:
  rootUrl: https://admin.example.shop
  service:
    annotations: {}
    type: ClusterIP
  ingress:
    enabled: false
    path: ""
    annotations: {}
    livenessPath:
    tls:
      enabled: false
      secretName: tls-secret
api:
  internalAlias: api
  replicaCount: 2
  image:
    repository: reactioncommerce/reaction
    tag: 3.7.1
    pullPolicy: IfNotPresent
    # imagePullSecret:
  rootUrl: https://api.example.shop
  service:
    annotations: {}
    type: ClusterIP
  ingress:
    enabled: false
    path: ""
    annotations: {}
    livenessPath:
    tls:
      enabled: false
      secretName: tls-secret
identity:
  internalAlias: identity
  replicaCount: 2
  image:
    repository: reactioncommerce/identity
    tag: 3.0.0
    pullPolicy: IfNotPresent
    # imagePullSecret:
  rootUrl: https://identity.example.shop
  service:
    annotations: {}
    type: ClusterIP
  ingress:
    enabled: false
    path: ""
    annotations: {}
    livenessPath:
    tls:
      enabled: false
      secretName: tls-secret
web:
  internalAlias: web
  replicaCount: 2
  image:
    repository: reactioncommerce/example-storefront
    tag: 3.0.0
    pullPolicy: IfNotPresent
    # imagePullSecret:
  rootUrl: https://www.example.shop
  service:
    annotations: {}
    type: ClusterIP
  ingress:
    enabled: false
    path: ""
    annotations: {}
    livenessPath:
    tls:
      enabled: false
      secretName: tls-secret
