admin:
  replicaCount: 2
  image:
    repository: reactioncommerce/admin
    tag: 3.0.0-beta.6
    pullPolicy: IfNotPresent
    # imagePullSecret:
  rootUrl: https://admin.example.shop
  storeFrontUrl: https://www.example.shop
