apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: admin
  name: admin
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: admin
    spec:
      containers:
      - env:
        - name: METEOR_DISABLE_OPTIMISTIC_CACHING
          value: "1"
        - name: METEOR_WATCH_POLLING_INTERVAL_MS
          value: "10000"
        - name: MONGO_OPLOG_URL
          value: mongodb://mongo.reaction.localhost:27017/local
        - name: MONGO_URL
          value: mongodb://mongo.reaction.localhost:27017/reaction
        - name: OAUTH2_ADMIN_URL
          value: http://hydra.reaction.localhost:4445
        - name: OAUTH2_IDP_PUBLIC_CHANGE_PASSWORD_URL
          value: http://localhost:4100/account/change-password?email=EMAIL&from=FROM
        - name: OAUTH2_PUBLIC_URL
          value: http://localhost:4444
        - name: PORT
          value: "4080"
        - name: PUBLIC_FILES_BASE_URL
          value: http://localhost:3000
        - name: PUBLIC_GRAPHQL_API_URL_HTTP
          value: http://localhost:3000/graphql
        - name: PUBLIC_GRAPHQL_API_URL_WS
          value: ws://localhost:3000/graphql
        - name: PUBLIC_I18N_BASE_URL
          value: http://localhost:3000
        - name: PUBLIC_STOREFRONT_HOME_URL
          value: http://localhost:4000
        - name: ROOT_URL
          value: http://localhost:4080
        image: reactioncommerce/admin:3.0.0-beta.6
        name: admin
        ports:
        - containerPort: 4080
        - containerPort: 9229
        resources: {}
      restartPolicy: Always
status: {}
