apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "reactioncommerce.name" . }}
    component: admin
    chart: {{ template "reactioncommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "reactioncommerce.fullname" . }}-admin
  namespace: {{ .Release.Namespace | quote }} 
spec:
  selector:
    matchLabels:
      app: {{ template "reactioncommerce.name" . }}
      component: admin
      release: {{ .Release.Name }}
  replicas: {{ .Values.admin.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "reactioncommerce.name" . }}
        component: admin
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-admin
        image: "{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag }}"
        imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
        ports:
          - name: admin
            containerPort: 4080
            protocol: TCP
          # - name: inspection
          #   containerPort: 9229
          #   protocol: TCP
      - env:
        - name: METEOR_DISABLE_OPTIMISTIC_CACHING
          value: "1"
        - name: METEOR_WATCH_POLLING_INTERVAL_MS
          value: "10000"
        - name: MONGO_OPLOG_URL
          value: mongodb://mongo.reaction.localhost:27017/local
        - name: MONGO_URL
          value: mongodb://mongo.reaction.localhost:27017/reaction
        - name: OAUTH2_ADMIN_URL
          value: http://hydra.reaction.localhost:4445
        - name: OAUTH2_IDP_PUBLIC_CHANGE_PASSWORD_URL
          value: http://localhost:4100/account/change-password?email=EMAIL&from=FROM
        - name: OAUTH2_PUBLIC_URL
          value: http://localhost:4444
        - name: PORT
          value: "4080"
        - name: PUBLIC_FILES_BASE_URL
          value: http://localhost:3000
        - name: PUBLIC_GRAPHQL_API_URL_HTTP
          value: http://localhost:3000/graphql
        - name: PUBLIC_GRAPHQL_API_URL_WS
          value: ws://localhost:3000/graphql
        - name: PUBLIC_I18N_BASE_URL
          value: http://localhost:3000
        - name: PUBLIC_STOREFRONT_HOME_URL
          value: {{ .Values.admin.storeFrontUrl }}
        - name: ROOT_URL
          value: {{ .Values.admin.rootUrl }}
