apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - env:
        - name: MONGO_URL
          value: mongodb://mongo.reaction.localhost:27017/reaction
        - name: ROOT_URL
          value: http://localhost:3000
        - name: STRIPE_API_KEY
          value: YOUR_PRIVATE_STRIPE_API_KEY
        image: reactioncommerce/reaction:3.7.1
        name: api
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
