{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "reactioncommerce.name" . }}
    component: api
    chart: {{ template "reactioncommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "reactioncommerce.fullname" . }}-api
  namespace: {{ .Release.Namespace | quote }} 
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "reactioncommerce.name" . }}
      component: api
      release: {{ .Release.Name }}
  replicas: {{ .Values.api.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "reactioncommerce.name" . }}
        component: api
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-api
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        ports:
          - name: api
            containerPort: 3000
            protocol: TCP
        env:
        - name: MONGO_URL
          value: mongodb://mongo.reaction.localhost:27017/reaction
        - name: ROOT_URL
          value: {{ .Values.api.rootUrl }}
        - name: STRIPE_API_KEY
          value: {{ .Values.global.stripeKey }}
{{- end }}
