apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: identity
  name: identity
spec:
  ports:
  - name: "4100"
    port: 4100
    targetPort: 4100
  selector:
    io.kompose.service: identity
status:
  loadBalancer: {}
